base_url: "/blog"
theme: jekyll-theme-midnight
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]