base_url: "/blog"
url: "https://merelylogical.github.io"
remote_theme: "just-the-docs/just-the-docs@v0.4.0.rc3"
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
color_scheme: dark
callouts:
  highlight:
    color: blue
  todo:
    title: Todo
    color: yellow
  note:
    title: Note
    color: green
  warning:
    title: Warning
    color: red
